apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: "/etc/kubernetes/simulator_kubeconfig.conf"
profiles:
  - schedulerName: kubernetes-default-scheduler
